// STRINGS ---------------------------------------------------------------------
#define STR_COMMAND_PROMPT "> "
#define STR_BOOT_PRE_MESSAGE "\r\nleanmodem is starting up"
#define STR_BOOT_POST_MESSAGE "Ready. Enter 'help' for assistance"
#define STR_COMMAND_UNRECOGNIZED "Command '%s' unknown"
#define STR_GREETING "Hey! How are you doing?"
#define STR_NOT_IMPLEMENTED "Not implemented yet!"
#define STR_SSID_SET "SSID set to '%s'."
#define STR_NULL_SSID_UNSUPPORTED "NULL SSIDs are not supported."
#define STR_PASSWORD_SET "Password set to '%s'."
#define STR_PASSWORD_SET_BLANK "Not using WiFi password."
#define STR_CONNECTION_ERROR "Failed to connect"
#define STR_DISCONNECTED "Disconnected."
#define STR_SSID_MISSING "Please set an SSID."
#define STR_UNREACHABLE_SSID "The SSID could not be reached."
#define STR_CONNECTED_WITH_IP "Connected to '%s1' with IP %s2"
#define STR_CONNECTION_FAILED "Failed to connect. Check password."
#define STR_INVALID_ARGUMENTS "Invalid arguments."
#define STR_SCANNING "Scanning networks..."
#define STR_NETWORKS_FOUND "Networks found: "
#define STR_NOT_CONNECTED "You are not connected."
#define STR_OPEN_FAILED "Failed to open."
#define STR_OPEN_SUCCESSFUL "Host connected."
#define STR_OK "Ok."
#define STR_NOT_SET "[NOT SET]"
#define STR_YES "YES"
#define STR_NO "NO"
#define STR_DIRECTORY_USER_TITLE "Listing user files:"
#define STR_DIRECTORY_SYSTEM_TITLE "Listing system files:"
#define STR_DIRECTORY_EMPTY "  [Empty]"
#define STR_DIRECTORY_ENTRY "  %d %s"
#define STR_DIRECTORY_TOTAL "  Total: %d bytes"
#define STR_DIRECTORY_USED "  Used : %d bytes"
#define STR_DIRECTORY_FREE "  Free : %d bytes"
#define STR_PLEASE_WAIT "Please wait."
#define STR_FORMAT_PROMPT "THIS WILL ERASE ALL FILES! Continue? (y/n): "
#define STR_FORMAT_OK "Format complete."
#define STR_FORMAT_FAILED "Format error."
#define STR_FORMAT_CANCELED "Format cancelled."
#define STR_DEVICE_WILL_RESTART "Your device will restart soon."
#define STR_USER_INPUT_YES "y"
#define STR_COPY_COMPLETED "Copy complete."
#define STR_ARGUMENT_CONFIG_SAVE "save"
#define STR_ARGUMENT_CONFIG_LOAD "load"
#define STR_ARGUMENT_FILES_SYSTEM "-s"
#define STR_HOST_UNAVAILABLE "Host unavailable."
#define STR_MONDAY "Monday"
#define STR_TUESDAY "Tuesday"
#define STR_WEDNESDAY "Wednesday"
#define STR_THURSDAY "Thursday"
#define STR_FRIDAY "Friday"
#define STR_SATURDAY "Saturday"
#define STR_SUNDAY "Sunday"
#define STR_FILE_NOT_FOUND "File not found."
#define STR_FILE_ERASE_SUCCESS "File erased."
#define STR_FILE_ERASE_FAILED "File could not be erased"
