// STRINGS ---------------------------------------------------------------------
#define STR_OK "Ok"
#define STR_YES "Yes"
#define STR_NO "No"
#define STR_WAIT "Wait"
#define STR_USER_INPUT_YES "y"
#define STR_USER_INPUT_NO "y"

#define STR_SYSTEM_PROMPT "> "
#define STR_SYSTEM_PRE "\r\nleanmodem is starting up"
#define STR_SYSTEM_POST "Ready. Enter 'help' for assistance"
#define STR_SYSTEM_WILL_RESTART "System will restart"
#define STR_NOT_SUPPORTED "Not supported"

#define STR_CONFIG_NOT_SET "[NOT SET]"
#define STR_CONFIG_ARG_SAVE "save"
#define STR_CONFIG_ARG_LOAD "load"

#define STR_NETWORK_SSID_MISSING "Missing SSID"
#define STR_NETWORK_SSID_UNREACHABLE "Unreachable SSID"
#define STR_NETWORK_SCANNING "Scanning networks..."
#define STR_NETWORK_FOUND "%d networks found"
#define STR_NETWORK_UNAVAILABLE "Network unavailable"
#define STR_NETWORK_HOST_UNAVAILABLE "Host unavailable"
#define STR_NETWORK_CONNECTED_TO "Connected to '%s1' with IP %s2"
#define STR_NETWORK_DISCONNECTED "Disconnected"
#define STR_NETWORK_CONNECTION_FAILED "Connection failed"

#define STR_FILES_USER_TITLE "Listing user files:"
#define STR_FILES_SYSTEM_TITLE "Listing system files:"
#define STR_FILES_EMPTY "  [Empty]"
#define STR_FILES_ENTRY "  %d %s"
#define STR_FILES_TOTAL_BYTES "Total: %d bytes"
#define STR_FILES_USED_BYTES "Used : %d bytes"
#define STR_FILES_FREE_BYTES "Free : %d bytes"
#define STR_FILES_ARG_SYSTEM "-s"
#define STR_FILES_NOT_FOUND "File not found"
#define STR_FILES_ERASE_SUCCESS "File erased"

#define STR_COPY_STANDARD_INPUT "stdin"
#define STR_COPY_STANDARD_OUTPUT "stdout"
#define STR_COPY_PORT_MISSING "Port missing"
#define STR_COPY_TCP_PREFIX "tcp://"
#define STR_COPY_HTTP_PREFIX "http://"

#define STR_ERROR_COMMAND_UNRECOGNIZED "'%s' unrecognized"
#define STR_ERROR_NOT_IMPLEMENTED "Not implemented"
#define STR_ERROR_INVALID_ARGUMENTS "Invalid arguments"
#define STR_ERROR_UNKNOWN "Unknown error"

#define STR_FORMAT_PROMPT "THIS WILL ERASE ALL FILES! Continue? (y/n): "
#define STR_FORMAT_OK "Format complete"
#define STR_FORMAT_FAILED "Format error"
#define STR_FORMAT_CANCELED "Format cancelled"

#define STR_CALENDAR_DAY_MONDAY "Monday"
#define STR_CALENDAR_DAY_TUESDAY "Tuesday"
#define STR_CALENDAR_DAY_WEDNESDAY "Wednesday"
#define STR_CALENDAR_DAY_THURSDAY "Thursday"
#define STR_CALENDAR_DAY_FRIDAY "Friday"
#define STR_CALENDAR_DAY_SATURDAY "Saturday"
#define STR_CALENDAR_DAY_SUNDAY "Sunday"
#define STR_CALENDAR_MONTH_JANUARY "January"
#define STR_CALENDAR_MONTH_FEBRUARY "February"
#define STR_CALENDAR_MONTH_MARCH "March"
#define STR_CALENDAR_MONTH_MAY "May"
#define STR_CALENDAR_MONTH_JUNE "June"
#define STR_CALENDAR_MONTH_JULY "July"
#define STR_CALENDAR_MONTH_AUGUST "August"
#define STR_CALENDAR_MONTH_SEPTEMBER "September"
#define STR_CALENDAR_MONTH_OCTOBER "October"
#define STR_CALENDAR_MONTH_NOVEMBER "November"
#define STR_CALENDAR_MONTH_DECEMBER "December"
#define STR_CALENDAR_MONTH_JAN "Jan"
#define STR_CALENDAR_MONTH_FEB "Feb"
#define STR_CALENDAR_MONTH_MAR "Mar"
#define STR_CALENDAR_MONTH_MAY "May"
#define STR_CALENDAR_MONTH_JUN "Jun"
#define STR_CALENDAR_MONTH_JUL "Jul"
#define STR_CALENDAR_MONTH_AUG "Aug"
#define STR_CALENDAR_MONTH_SEP "Sep"
#define STR_CALENDAR_MONTH_OCT "Oct"
#define STR_CALENDAR_MONTH_NOV "Nov"
#define STR_CALENDAR_MONTH_DEC "Dec"
